<?php

namespace Database\Seeders;

use App\Models\AIRID_Photo;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PhotoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //

        $list_photos = [
            [
                "titre_photo"=>"Visit Gate Foundation",
                "description"=>"Mr David Malone visited our GLP-compliant facility",
                "statut_photo"=>"principal",
                "nom_photo"=>"gates/IMG_0933.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"gates",
                "date_event"=>"2025-03-06",
            ],
            [
                "titre_photo"=>"Visit Gate Foundation",
                "description"=>"Mr David Malone visited our GLP-compliant facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"gates/IMG_0857.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"gates",
                "date_event"=>"2025-03-06",
            ],
            [
                "titre_photo"=>"Visit Gate Foundation",
                "description"=>"Mr David Malone visited our GLP-compliant facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"gates/IMG_0865.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"gates",
                "date_event"=>"2025-03-06",
            ],
            [
                "titre_photo"=>"Visit IVCC",
                "description"=>"IVCC visited our GLP-compliant facility",
                "statut_photo"=>"principal",
                "nom_photo"=>"ivcc/IMG_0770.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"ivcc",
                "date_event"=>"2025-03-06",
            ],
            [
                "titre_photo"=>"Visit IVCC",
                "description"=>"IVCC visited our GLP-compliant facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"ivcc/IMG_0426.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"ivcc",
                "date_event"=>"2025-03-06",
            ],
            [
                "titre_photo"=>"Visit IVCC",
                "description"=>"IVCC visited our GLP-compliant facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"ivcc/IMG_0468.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"ivcc",
                "date_event"=>"2025-03-06",
            ],
            [
                "titre_photo"=>"Visit IVCC",
                "description"=>"IVCC visited our GLP-compliant facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"ivcc/IMG_0480.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"ivcc",
                "date_event"=>"2025-03-06",
            ],
            [
                "titre_photo"=>"Visit IVCC",
                "description"=>"IVCC visited our GLP-compliant facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"ivcc/IMG_0524.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"ivcc",
                "date_event"=>"2025-03-06",
            ],
            [
                "titre_photo"=>"Visit IVCC",
                "description"=>"IVCC visited our GLP-compliant facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"ivcc/IMG_0538.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"ivcc",
                "date_event"=>"2025-03-06",
            ],
            [
                "titre_photo"=>"Visit IVCC",
                "description"=>"IVCC visited our GLP-compliant facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"ivcc/IMG_0553.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"ivcc",
                "date_event"=>"2025-03-06",
            ],
            [
                "titre_photo"=>"Visit IVCC",
                "description"=>"IVCC visited our GLP-compliant facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"ivcc/IMG_0598.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"ivcc",
                "date_event"=>"2025-03-06",
            ],
            [
                "titre_photo"=>"Visit IVCC",
                "description"=>"IVCC visited our GLP-compliant facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"ivcc/IMG_0766.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"ivcc",
                "date_event"=>"2025-03-06",
            ],
            [
                "titre_photo"=>"Visit IVCC",
                "description"=>"IVCC visited our GLP-compliant facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"ivcc/IMG_0831.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"ivcc",
                "date_event"=>"2025-03-06",
            ],
            [
                "titre_photo"=>"PLUS Project Process Evaluation Workshop",
                "description"=>"The Process Evaluation Team Was in our facility to hold a Workshop",
                "statut_photo"=>"principal",
                "nom_photo"=>"process_evaluation/IMG_0938.jpg",
                "categorie_photo"=>"Project",
                "tag"=>"process_evaluation",
                "date_event"=>"2025-03-11",
            ],
            [
                "titre_photo"=>"PLUS Project Process Evaluation Workshop",
                "description"=>"The Process Evaluation Team Was in our facility to hold a Workshop",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"process_evaluation/IMG_0945.jpg",
                "categorie_photo"=>"Project",
                "tag"=>"process_evaluation",
                "date_event"=>"2025-03-11",
            ],
            [
                "titre_photo"=>"PLUS Project Process Evaluation Workshop",
                "description"=>"The Process Evaluation Team Was in our facility to hold a Workshop",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"process_evaluation/IMG_0974.jpg",
                "categorie_photo"=>"Project",
                "tag"=>"process_evaluation",
                "date_event"=>"2025-03-11",
            ],
            [
                "titre_photo"=>"PLUS Project Process Evaluation Workshop",
                "description"=>"The Process Evaluation Team Was in our facility to hold a Workshop",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"process_evaluation/IMG_0977.jpg",
                "categorie_photo"=>"Project",
                "tag"=>"process_evaluation",
                "date_event"=>"2025-03-11",
            ],
            [
                "titre_photo"=>"PLUS Project Process Evaluation Workshop",
                "description"=>"The Process Evaluation Team Was in our facility to hold a Workshop",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"process_evaluation/IMG_0978.jpg",
                "categorie_photo"=>"Project",
                "tag"=>"process_evaluation",
                "date_event"=>"2025-03-11",
            ],
            [
                "titre_photo"=>"Visit of RBM Vector Control Working Group (VCWG)",
                "description"=>"The RBM Vector Control Working Group visited our Facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"rbm_vcwg/IMG_1430.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"rbm_vcwg",
                "date_event"=>"2025-03-02",
            ],
            [
                "titre_photo"=>"Visit of RBM Vector Control Working Group (VCWG)",
                "description"=>"The RBM Vector Control Working Group visited our Facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"rbm_vcwg/IMG_1450.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"rbm_vcwg",
                "date_event"=>"2025-03-02",
            ],
            [
                "titre_photo"=>"Visit of RBM Vector Control Working Group (VCWG)",
                "description"=>"The RBM Vector Control Working Group visited our Facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"rbm_vcwg/IMG_1460.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"rbm_vcwg",
                "date_event"=>"2025-03-02",
            ],
            [
                "titre_photo"=>"Visit of RBM Vector Control Working Group (VCWG)",
                "description"=>"The RBM Vector Control Working Group visited our Facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"rbm_vcwg/IMG_1501.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"rbm_vcwg",
                "date_event"=>"2025-03-02",
            ],
            [
                "titre_photo"=>"Visit of RBM Vector Control Working Group (VCWG)",
                "description"=>"The RBM Vector Control Working Group visited our Facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"rbm_vcwg/IMG_1502.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"rbm_vcwg",
                "date_event"=>"2025-03-02",
            ],
            [
                "titre_photo"=>"Visit of RBM Vector Control Working Group (VCWG)",
                "description"=>"The RBM Vector Control Working Group visited our Facility",
                "statut_photo"=>"principal",
                "nom_photo"=>"rbm_vcwg/IMG_1593.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"rbm_vcwg",
                "date_event"=>"2025-03-02",
            ],
            [
                "titre_photo"=>"Visit of RBM Vector Control Working Group (VCWG)",
                "description"=>"The RBM Vector Control Working Group visited our Facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"rbm_vcwg/IMG_1601.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"rbm_vcwg",
                "date_event"=>"2025-03-02",
            ],
            [
                "titre_photo"=>"Visit of RBM Vector Control Working Group (VCWG)",
                "description"=>"The RBM Vector Control Working Group visited our Facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"rbm_vcwg/IMG_1603.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"rbm_vcwg",
                "date_event"=>"2025-03-02",
            ],
            [
                "titre_photo"=>"Visit of RBM Vector Control Working Group (VCWG)",
                "description"=>"The RBM Vector Control Working Group visited our Facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"rbm_vcwg/IMG_1606.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"rbm_vcwg",
                "date_event"=>"2025-03-02",
            ],
            [
                "titre_photo"=>"Visit of RBM Vector Control Working Group (VCWG)",
                "description"=>"The RBM Vector Control Working Group visited our Facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"rbm_vcwg/principal.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"rbm_vcwg",
                "date_event"=>"2025-03-02",
            ],
            [
                "titre_photo"=>"Visit PLUS Project PE Team",
                "description"=>"The PLUS Project Process Evaluation Team visited our Facility",
                "statut_photo"=>"principal",
                "nom_photo"=>"visit_projet_plus/IMG_1165.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"visit_projet_plus",
                "date_event"=>"2025-03-13",
            ],
            [
                "titre_photo"=>"Visit PLUS Project PE Team",
                "description"=>"The PLUS Project Process Evaluation Team visited our Facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"visit_projet_plus/IMG_1121.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"visit_projet_plus",
                "date_event"=>"2025-03-13",
            ],
            [
                "titre_photo"=>"Visit PLUS Project PE Team",
                "description"=>"The PLUS Project Process Evaluation Team visited our Facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"visit_projet_plus/IMG_1130.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"visit_projet_plus",
                "date_event"=>"2025-03-13",
            ],
            [
                "titre_photo"=>"Visit PLUS Project PE Team",
                "description"=>"The PLUS Project Process Evaluation Team visited our Facility",
                "statut_photo"=>"secondaire",
                "nom_photo"=>"visit_projet_plus/IMG_1165.jpg",
                "categorie_photo"=>"Visits",
                "tag"=>"visit_projet_plus",
                "date_event"=>"2025-03-13",
            ],
        ];


        foreach ($list_photos as $key => $photo) {
            # code...

            $create_photo  = AIRID_Photo::create($photo);
        }
    }
}
